spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf642454e7sqyc2v0o.mysql.rds.aliyuncs.com/job_quartz
    username: root
    password: Tanliyuan123
server:
  port: 8082